### ISSUE TITLE
The API url is now using HTTPs

### ISSUE THREAD

**Issue by patrick91** [amio/alfred-emoji-finder#2]
If you run the workflow it won't work.

I changed the api url from `http://...` to `https://...` and then it worked :)

**Comment by ngryman** [comment]
👋 @amio, it would be super nice to make this very simple change. Also why not open-sourcing it so we could open a PR for you? Thanks!

**Comment by amio** [comment]
Sorry for missing this issue for so long! and thanks for ping me about this 😄

for the source code, you can double click the "Script Filter" in Alfred preference to view it:
```javascript
function run(argv) {

var app = Application.currentApplication()
app.includeStandardAdditions = true

var query = argv[0].replace(/'/g, '%27').split(' ').join('+')
var endpoint = 'https://emoji.getdango.com/api/emoji?q=' + query
var res = app.doShellScript('curl ' + endpoint)
var total = ''
var items = this.JSON.parse(res).results.map(function (item) {
  total += item.text
  return {
    'title': item.text,
    'arg': item.text
  }
})
var totalItem = [{
    'title': total,
    'arg': total
  }]

var output = this.JSON.stringify({
  'items': totalItem.concat(items)
});

return output;

}
```

![image](https://user-images.githubusercontent.com/215282/34659471-078d39bc-f474-11e7-8716-a03d7356ef0c.png)

**Comment by ngryman** [comment]
@amio Sure, I've done it. Thanks for the walkthrough though! My question was more, could you update it on Packal so it's available for others? Thanks!

**Comment by amio** [comment]
I didn't remember I have submited it to Packal 😅 thanks for reminding again!
It's been updated now.
